import "./globals.css";
import { Metadata } from "next";
import Header from "../components/Header";
import Footer from "../components/Footer"; // Impor Footer

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className="antialiased">
        <Header /> {/* Memasukkan komponen Header */}
        <main>{children}</main> {/* Tempat untuk konten dinamis */}
        <Footer /> {/* Memasukkan komponen Footer */}
      </body>
    </html>
  );
}
